### ISSUE TITLE
get utterance audio file

### ISSUE THREAD

**Issue by CoreyCole** [ewjmulder/alexa-proxy#1]
I'm building a proof-of-concept demonstration using Alexa and for it to work I need access to users audio. I have it working in an AVS web app where it is possible to get access to the mp3 audio file for each utterance.

I'd like to get this working with an actual Alexa device. Not for a production skill, just for a demo. If you check [this video here at 1:30](https://www.youtube.com/watch?v=PMHJ51SUpWU&feature=youtu.be&t=91), his Alexa is hooked up to their own "custom server" instead of Amazon's.

This allows him to use the audio files to authenticate the user. How is this possible? Would a proxy like this help me do this?

**Comment by ewjmulder** [comment]
Hi Corey, thanks for reaching out.

No, this proxy will not solve your problem. This is because of the split of the communication between the Alexa device and the Amazon server on one side and the Amazon server and the skill on the other side. This proxy is placed between the latter communication points, intercepting the request from the Amazon server to the skill and vice versa. That request/response does not contain any audio data, just the resulting action / command / question in text that is directed at the skill.

The communication between the Alexa device and the Amazon server (containing the actual audio) is secured and fixed to only work with Amazon servers. I'm not sure how exactly, but I guess the Alexa device has a hardcoded URL to post to and Amazon certificates installed to identify the server. So tampering with that will be very hard to do. You can ask Pindrop how they did it but I suspect they have a deal with Amazon that enables them to test with a modified Alexa device.

Good luck & regards, Erik

**Comment by CoreyCole** [comment]
Thank you for going out of your way and for providing me with a detailed and informative answer! If it is any interest to you, I've done more research on the topic and I think the way pindrop did it is through a hardware vulnerability.

Basically, you boot the alexa from an SD card which grants you root access. You can then copy over a script that streams the audio from the always-listening microphones to a 3rd party server. This only works with 1st generation, 1st iteration echo devices.

You can read about it here: 

Alexa, are you listening? Mark Barnes, 1 August 2017
https://labs.mwrinfosecurity.com/blog/alexa-are-you-listening

Amazon Echo Hardware Root via eMMC Debug Pins by echohacking on github
https://github.com/echohacking/wiki/wiki/Echo

A Survey of Various Method￼Enroll Voice s for Analyzing the Amazon Echo, The Citadel, The Military College of South Carolina
https://vanderpot.com/Clinton_Cook_Paper.pdf

**Comment by ewjmulder** [comment]
Hi Corey, thanks for your reply. Very interesting to read about the hardware hack. That seems like a plausible way for Pindrop to do what they did. If you're a bit handy with that you could use it too if you have a vulnerable device. Either way, good luck with your demo!
